!!python/object/new:pytorch_lightning.utilities.parsing.AttributeDict
dictitems:
  batchnorm: false
  data_split:
  - 4000
  - 100
  - 400
  dataset_class: GraphDataset
  edge_cut: 0.1
  factor: 0.95
  gpus: 4
  hard_cuts: null
  hidden: 1024
  hidden_activation: ReLU
  input_dir: /pscratch/sd/p/pmtuan/2023_ttbar_uncorrelated/metric_learning_11292882/
  layernorm: true
  log_wandb: true
  lr: 0.001
  max_epochs: 1000
  metric_mode: max
  metric_to_monitor: auc
  min_lr: 5.0e-05
  model: Filter
  nb_layer: 4
  node_features:
  - r
  - phi
  - z
  - cluster_x_1
  - cluster_y_1
  - cluster_z_1
  - cluster_x_2
  - cluster_y_2
  - cluster_z_2
  - count_1
  - charge_count_1
  - loc_eta_1
  - loc_phi_1
  - localDir0_1
  - localDir1_1
  - localDir2_1
  - lengthDir0_1
  - lengthDir1_1
  - lengthDir2_1
  - glob_eta_1
  - glob_phi_1
  - eta_angle_1
  - phi_angle_1
  - count_2
  - charge_count_2
  - loc_eta_2
  - loc_phi_2
  - localDir0_2
  - localDir1_2
  - localDir2_2
  - lengthDir0_2
  - lengthDir1_2
  - lengthDir2_2
  - glob_eta_2
  - glob_phi_2
  - eta_angle_2
  - phi_angle_2
  node_scales:
  - 1000
  - 3.14
  - 1000
  - 1000
  - 1000
  - 1000
  - 1000
  - 1000
  - 1000
  - 1
  - 1
  - 3.14
  - 3.14
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 3.14
  - 3.14
  - 3.14
  - 3.14
  - 1
  - 1
  - 3.14
  - 3.14
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 3.14
  - 3.14
  - 3.14
  - 3.14
  nodes: 1
  patience: 50
  precision: 32-true
  project: CF_2023_Ttbar_Uncorr_Filter
  ratio: 5
  scheduler: StepLR
  stage: edge_classifier
  stage_dir: /global/cfs/cdirs/m3443/data/GNN4ITK/CommonFrameworkExamples/2023_ttbar_uncorrelated/filter
  undirected: true
  warmup: 10
  weighting:
  - conditions:
      y: false
    weight: 1.0
  - conditions:
      y: true
    weight: 0.0
  - conditions:
      nhits:
      - 3
      - .inf
      pdgId:
      - not_in
      - - 11
        - -11
      primary: true
      pt:
      - 1000.0
      - .inf
      y: true
    weight: 4.0
