# CommonFramework configuration
stage: graph_construction
model: PyModuleMap
input_dir: /fs/ess/PLS0144/data/ITk-upgrade/CTD2023/feature_sets/ #MY_DATA_DIR/ATLAS-P2-ITK-23-00-03_Rel.21.9/ttbar/feature_store/
stage_dir: /fs/scratch/PLS0144/alina/ITk_Results/CTD2023/module_map/

# Dataset parameters
data_split: [0, 0, 100] # Number of [training, validation, testing] examples
module_map_path: /fs/ess/PLS0144/data/ITk-upgrade/CTD2023/model_store/module_map/MMtriplet_1GeV_3hits_noE__merged__sorted.txt
batch_size: 2000000

max_workers: 16