# CommonFramework configuration
stage: graph_construction
model: PyModuleMap
input_dir: /global/cfs/cdirs/m4439/CTD2023/
stage_dir: /pscratch/sd/a/alazar/cf/CTD_2023/module_map/

# Dataset parameters
data_split: [80, 10, 1000] #[7800, 1000, 1000] # Number of [training, validation, testing] examples
module_map_path: /global/cfs/cdirs/m4439/CTD2023/MMtriplet_1GeV_3hits_noE__merged__sorted.txt
batch_size: 4000000

max_workers: 16