# CommonFramework configuration
stage: graph_construction
model: PyModuleMap
input_dir: /pscratch/sd/a/alazar/cf/Example_1/feature_store/ # Should contain the files used in training and inference
stage_dir: /pscratch/sd/a/alazar/cf/Example_1/module_map/ # A directory to be created that will store logs, artifacts, and output data

# Dataset parameters
data_split: [0, 10, 10] # Number of [training, validation, testing] examples
module_map_path: /global/cfs/cdirs/m4439/Example_1/example_1_module_map.csv
batch_size: 4000000